apiVersion: apps/v1
kind: Deployment
metadata:
  name: inv-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inv-backend
  template:
    metadata:
      labels:
        app: inv-backend
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: backend
          image: ghcr.io/inventory-proj/inv-backend:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "administrator" # Твой юзер из .env
            - name: POSTGRES_DB
              value: "inventory"     # Твоя БД из .env
            - name: DB_HOST
              value: "db"            # Имя сервиса базы внутри K8s (вместо localhost)
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: jwt-secret-key
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 8000
  selector:
    app: inv-backend
